#后端端口号
server:
  port: 9090
#数据库连接参数
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/SpringBootLearn?useUnicode=useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 234869
# 使用swagger，让他不报错？
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# mybatis plus逻辑删除配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 数据库运行log

#文件存储
files:
  upload:
    path: D:/JAVA/java_learn/2_webstudy/html/idea_web/.project_store_files/SpringBootLearn_store_files/UploadFiles/